[package]
name = "tauri-ios-demo"
version = "1.0.0"
description = "iOS 系统信息查看器"
authors = ["you"]
edition = "2021"

[lib]
name = "tauri_ios_demo_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"